name: Deploy sphinx docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_docs.txt

      - name: install project
        run: |
          pip install -e .

      - name: debug imports
        run: |
          python -c "import sys; print('sys.path:', sys.path)"
          python -c "import synapticonn; print('synapticonn imported from:', synapticonn.__file__)"

      - name: build docs
        run: |
          sphinx-build -b html docs/ docs/_build/html

      - name: deploy to gh pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghp-import -n -p -f docs/_build/html

      - name: print working directory
        run: |
          echo "current directory: $(pwd)"
          ls -la